[tool.poetry]
name = "assignment-3"
version = "0.1.0"
description = ""
authors = ["Molly Jones <mojones.e@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
librosa = "^0.10.2.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
